### ISSUE TITLE
[EPIC] Refactor PushmiPullyu to create AIP post-Fedora

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/pushmi_pullyu#192]
This is an epic issue to capture the required work needed to refactor PMPY and construct the AIP needed for preservation from non-Fedora data sources. These files are currently be downloaded/constructed through Fedora in this file: https://github.com/ualbertalib/pushmi_pullyu/blob/master/lib/pushmi_pullyu/aip/downloader.rb

The refactoring work requires the reconstruction of these following files, following current file structures/formats, but acquire information from PQ. The refactored PMPY needs to work with the intergration_postmigration branch: https://github.com/ualbertalib/jupiter/tree/integration_postmigration
Works done in the integration_postmigration, and [OAISYS](https://github.com/ualbertalib/oaisys) and the gem [acts_as_rdfable](https://github.com/ualbertalib/oaisys/blob/master/Gemfile#L18) can probably be leveraged to create RDFs needed for the reconstruction of the triple N3 files. 

Work required:
- [x] Object metadata into object_metadata.n3
- [x] Construct the ordering of the file into file_order.xml
- [x] FileSet metadata into file_set_metadata.n3, with user id replaced by actual user email
- [x] File metadata into original_file_metadata.n3
- [x] File's technical metadata, with content_fixity_report.n3
- [x] File download (Now ActiveStorage manages the file paths and actual files saved in Gluster FS on /era_assets)

**Comment by weiweishi** [comment]
Additional information @lagoan @mbarnett :
- Lightweight AIP 2.0 specs:
https://docs.google.com/document/d/1U1aS5yJuISeC1hEVlF2qkvaW1ZoWqVLNRjqBw2kZgXs/edit
- Sample AIP based on 2.0 specs is at:
https://drive.google.com/open?id=1XSNe961PxOfVitkfLOgQG2j3V8wiqFfy
